###
POST http://localhost:1323/user HTTP/1.1
Content-Type: application/json

{
    "name":"marce",
    "password":"1233",
    "email":"marce@gmail.com"
}

###
GET http://localhost:1323/user HTTP/1.1
Content-Type: application/json

{
    "name":"marce",
    "password":"1233"
}

###
PATCH http://localhost:1323/user HTTP/1.1
Content-Type: application/json

{
    "id":"645d02b10ea69f3b780ea21e",
    "name":"juan",
    "password":"1318",
    "email":"juan@gmail.com"
}


###
PUT http://localhost:1323/user/645d02b10ea69f3b780ea21e HTTP/1.1

###
POST http://localhost:1323/enterprise HTTP/1.1
Content-Type: application/json

{
    "name":"Adidas",
    "users":[
        "64660d430aa0b1e3b4c1605a",
        "6466367bd6907fd2515c0758",
        "6473cfdf37e32fbfa868a3de"
    ]
}