###
POST http://localhost:1323/user/register/ HTTP/1.1
Content-Type: application/json

{
    "name":"joaco",
    "password":"1233",
    "email":"algo@gmail.com"
}

###
POST  http://localhost:1323/user/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"marce@gmail.com",
    "password":"1233"
}

###
PATCH http://localhost:1323/user/ HTTP/1.1
Content-Type: application/json

{
    "id":"6552a02bc4a40647544dea54",
    "name":"juan",
    "password":"1318",
    "email":"juan@gmail.com"
}


###
PUT http://localhost:1323/user/6552a1351ce562e34c026802/ HTTP/1.1

###
POST http://localhost:1323/enterprise/ HTTP/1.1
Content-Type: application/json

{
    "name":"Adidas",
    "users":[
        "64660d430aa0b1e3b4c1605a",
        "6466367bd6907fd2515c0758",
        "6473cfdf37e32fbfa868a3de"
    ]
}

###
GET http://localhost:1323/enterprise/ HTTP/1.1